version: "3"
services: 
  mongodb:
    image: mongo
    ports:
      - 27017:27017 # docker:host
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    volumes:
      - db-data:/data/db # именнованный том
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=toor
      - ME_CONFIG_MONGODB_SERVER=mongodb # имя контейнера с базой данных
    depends_on:
      - mongodb
volumes:
  db-data:
    driver: local
